services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '3333:3333'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - upload
  db:
    container_name: postgres
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - '$POSTGRES_PORT:$POSTGRES_PORT'
    env_file:
      - .env
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
      - db:/bitnami/postgresql
    networks:
      - upload
      - db

volumes:
  db:

networks:
  db:
    driver: bridge #default
  upload:
    driver: bridge #default
