services:
  app:
    build: .
    ports:
      - '3333:3333'
    env_file:
      - .env
  # pg:
  #   image: bitnami/postgresql:latest
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=docker
  #     - POSTGRES_DB=upload
  #   volumes:
  #     - './docker:/docker-entrypoint-initdb.d'
