services:
  app:
    build: .
    ports:
      - '3333:3333'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - upload
  db:
    container_name: postgres
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
      - db:/bitnami/postgresql
    networks:
      - upload
      - db

volumes:
  db:

networks:
  db:
    driver: bridge #default
  upload:
    driver: bridge #default
