name: pipe
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout # used to identify an step, it should be used to get infos from this step easily
        uses: actions/checkout@v4

      - name: Configure NodeJS
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install PNPM
        id: install-pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        id: install-dependencies
        run: |
          pnpm install

      - name: Configure AWS Credentials
        id: configure-aws-credentials # used to identify an step, it should be used to get infos from this step easily
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to AWS ECR
        id: login-ecr # used to identify an step, it should be used to get infos from this step easily
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        id: setup-docker-buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7) # Use $GITHUB_SHA to get commit sha, use | head -c7 to get first 7 chars and pass it to SHA (by echo command)
          echo "sha=$SHA" >> $GITHUB_OUTPUT  # Get $SHA value and concat it with sha=, then save it into $GITHUB_OUTPUT to let it available out this step

      - name: Build and Load Image
        id: load-image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ steps.generate_tag.outputs.sha }}

      - name: Run Trivy Vulnerability Scanner
        id: run-trivy-scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ steps.generate_tag.outputs.sha }}'
          format: 'table'
          # exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Build and Push the Image to AWS ECR
        id: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ steps.generate_tag.outputs.sha }}
      - name: Deploy to App Runner
        id: deploy-app-runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: upload-server
          image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ steps.generate_tag.outputs.sha }}
          region: ${{ vars.AWS_REGION }}
          cpus: 1
          memory: 2
          port: 3333
