name: pipe
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout # used to identify an step, it should be used to get infos from this step easily
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: configure-aws-credentials # used to identify an step, it should be used to get infos from this step easily
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to AWS ECR
        id: login-ecr # used to identify an step, it should be used to get infos from this step easily
        uses: aws-actions/amazon-ecr-login@v2
